#!/bin/sh

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
export HOME=/root
export TERM=vt100

mount -a

ifconfig lo 127.0.0.1

cd $HOME

while /bin/true; do

  setsid sh -c 'exec sh < /dev/hvc0 > /dev/hvc0 2>&1'

done